Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -56,8 +56,20 @@ jobs:
     steps:
         - uses: actions/checkout@v4
         - uses: hashicorp/setup-terraform@v3
+
+          # Run a terraform fmt to check syntax
+        - name: Terraform Format
+          id: fmt
+          run: terraform fmt -check
+
+           # Run a terraform validate
+        - name: Terraform Validate
+          id: validate
+          # Run even if formatting fails
+          if: success() || failure()
+          run: terraform validate -no-color
                 
-        - name: Terraform Init
+        - name: Terraform apply
           id: init
           run: cd /opt/terraform/ && sudo terraform apply -auto-approve
 
